STATE_DATA = {
    'AL': {'name': 'Alabama', 'votes': 9},
    'AK': {'name': 'Alaska', 'votes': 3},
    'AZ': {'name': 'Arizona', 'votes': 11},
    'AR': {'name': 'Arkansas', 'votes': 6},
    'CA': {'name': 'California', 'votes': 54},
    'CO': {'name': 'Colorado', 'votes': 10},
    'CT': {'name': 'Connecticut', 'votes': 7},
    'DE': {'name': 'Delaware', 'votes': 3},
    'DC': {'name': 'District of Columbia', 'votes': 3},
    'FL': {'name': 'Florida', 'votes': 30},
    'GA': {'name': 'Georgia', 'votes': 16},
    'HI': {'name': 'Hawaii', 'votes': 4},
    'ID': {'name': 'Idaho', 'votes': 4},
    'IL': {'name': 'Illinois', 'votes': 19},
    'IN': {'name': 'Indiana', 'votes': 11},
    'IA': {'name': 'Iowa', 'votes': 6},
    'KS': {'name': 'Kansas', 'votes': 6},
    'KY': {'name': 'Kentucky', 'votes': 8},
    'LA': {'name': 'Louisiana', 'votes': 8},
    'ME': {'name': 'Maine', 'votes': 4},
    'MD': {'name': 'Maryland', 'votes': 10},
    'MA': {'name': 'Massachusetts', 'votes': 11},
    'MI': {'name': 'Michigan', 'votes': 15},
    'MN': {'name': 'Minnesota', 'votes': 10},
    'MS': {'name': 'Mississippi', 'votes': 6},
    'MO': {'name': 'Missouri', 'votes': 10},
    'MT': {'name': 'Montana', 'votes': 4},
    'NE': {'name': 'Nebraska', 'votes': 5},
    'NV': {'name': 'Nevada', 'votes': 6},
    'NH': {'name': 'New Hampshire', 'votes': 4},
    'NJ': {'name': 'New Jersey', 'votes': 14},
    'NM': {'name': 'New Mexico', 'votes': 5},
    'NY': {'name': 'New York', 'votes': 28},
    'NC': {'name': 'North Carolina', 'votes': 16},
    'ND': {'name': 'North Dakota', 'votes': 3},
    'OH': {'name': 'Ohio', 'votes': 17},
    'OK': {'name': 'Oklahoma', 'votes': 7},
    'OR': {'name': 'Oregon', 'votes': 8},
    'PA': {'name': 'Pennsylvania', 'votes': 19},
    'RI': {'name': 'Rhode Island', 'votes': 4},
    'SC': {'name': 'South Carolina', 'votes': 9},
    'SD': {'name': 'South Dakota', 'votes': 3},
    'TN': {'name': 'Tennessee', 'votes': 11},
    'TX': {'name': 'Texas', 'votes': 40},
    'UT': {'name': 'Utah', 'votes': 6},
    'VT': {'name': 'Vermont', 'votes': 3},
    'VA': {'name': 'Virginia', 'votes': 13},
    'WA': {'name': 'Washington', 'votes': 12},
    'WV': {'name': 'West Virginia', 'votes': 4},
    'WI': {'name': 'Wisconsin', 'votes': 10},
    'WY': {'name': 'Wyoming', 'votes': 3}
}
